CREATE TABLE IF NOT EXISTS air_quality_readings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sensor_id VARCHAR(50) NOT NULL,
  room VARCHAR(50) NOT NULL,
  pm25 FLOAT NOT NULL,
  co2 INT NOT NULL,
  air_status VARCHAR(50) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
